/** Stable UI keys. Help is documentation, never part of serialized project data. */
const entry = (chapter: string, label: string, text: string) => ({ chapter, label, text })
export const fieldHelp = {
  'identity.title': entry('inspector', 'Название', 'Короткая подпись элемента, до 300 символов. Переименование не меняет ID и существующие связи.'),
  'identity.description': entry('inspector', 'Описание', 'Смысл и ответственность элемента: зачем он нужен и какой результат даёт.'),
  'identity.notes': entry('inspector', 'Заметки', 'Дополнительные решения, открытые вопросы и критерии готовности.'),
  'identity.tags': entry('inspector', 'Теги', 'Метки через запятую. Помогают находить узлы в поиске по проекту.'),
  'identity.links': entry('inspector', 'Ссылки', 'HTTP/HTTPS-адреса источников и документации, по одному на строку.'),
  'identity.status': entry('inspector', 'Статус', 'Ваша оценка готовности: draft, configured, ready или disabled. Статус не заменяет проверку валидатором.'),
  'identity.color': entry('inspector', 'Цвет акцента', 'Визуальное выделение карточки. Не меняет тип узла или его поведение.'),
  'concept.convert': entry('concept', 'Преобразовать в', 'Уточните идею до инженерного типа. Текст, положение и связи сохранятся; преобразование можно отменить.'),
  'agent.role': entry('agent', 'Роль', 'Кем является агент и за какую часть результата отвечает.'),
  'agent.systemPrompt': entry('agent', 'System prompt', 'Цель, порядок действий, ограничения и формат ответа будущего агента.'),
  'agent.promptId': entry('agent', 'Prompt reference', 'Общий prompt проекта. При экспорте его текст предшествует локальным инструкциям агента.'),
  'agent.behavioralRules': entry('agent', 'Правила поведения', 'По одному правилу на строку: проверять источники, отмечать неопределённость, соблюдать ограничения.'),
  'agent.model.provider': entry('agent', 'Provider', 'Название планируемого провайдера модели. Доступность сервиса здесь не проверяется.'),
  'agent.model.name': entry('agent', 'Model', 'Имя модели для будущей реализации. Поле описывает выбор, но не подключает модель.'),
  'agent.model.parameters': entry('agent', 'Параметры модели (JSON)', 'JSON-объект настроек модели. Проверяется структура JSON, а не поддержка параметров конкретным API.'),
  'agent.context.memory': entry('agent', 'Память', 'Какие сведения агент должен помнить между шагами или обращениями.'),
  'agent.context.knowledge': entry('agent', 'Источники знаний', 'Документы, базы и другие источники, на которые должен опираться агент.'),
  'agent.context.attachedNodeIds': entry('agent', 'Прикреплённые данные', 'Ссылки на узлы проекта, содержащие необходимый контекст. Содержимое этих узлов не копируется.'),
  'agent.context.policy': entry('agent', 'Политика контекста', 'Правила отбора, обновления и ограничения контекста агента.'),
  'agent.toolIds': entry('agent', 'Connected tools', 'Инструменты Tool, которыми разрешено пользоваться агенту. Выбор не создаёт линии Tool access на Canvas.'),
  permissions: entry('tool', 'Разрешения', 'Планируемые ограничения доступа и действий, по одному на строку. Реальные права в этой версии не выдаются.'),
  input: entry('contracts', 'Входной контракт', 'Какие данные получает элемент: свободное описание, локальная JSON Schema или ссылка на общую схему.'),
  output: entry('contracts', 'Выходной контракт', 'Какой результат передаёт элемент следующему участнику системы.'),
  'execution.timeoutMs': entry('agent', 'Timeout (ms)', 'Предельное время ожидания в миллисекундах для будущей реализации. Сейчас это метаданные, а не работающий таймер.'),
  'execution.retries': entry('agent', 'Retries', 'Число повторных попыток при ошибке. Сохраняется в спецификации; Preview повторные запросы не выполняет.'),
  'execution.fallbackNodeId': entry('agent', 'Fallback', 'Запасной узел на случай ошибки. Ссылка хранится по ID и сохраняется при переименовании.'),
  'execution.errorPolicy': entry('agent', 'Обработка ошибок', 'Что должна делать будущая система при сбое: остановиться, повторить действие или передать задачу дальше.'),
  'tool.category': entry('tool', 'Категория', 'Назначение инструмента, например search, storage, API или filesystem.'),
  'tool.provider': entry('tool', 'Provider', 'Система или поставщик инструмента.'),
  'tool.reference': entry('tool', 'Endpoint / reference', 'Адрес или идентификатор будущей интеграции. Приложение не отправляет запрос по этому адресу.'),
  'tool.authentication.type': entry('tool', 'Authentication', 'none — без аутентификации; environment — имя переменной окружения; credential-ref — ссылка на учётные данные.'),
  'tool.authentication.reference': entry('tool', 'Имя ENV / credential ID', 'Укажите имя вроде SEARCH_API_KEY или идентификатор credentials. Никогда не вставляйте сам ключ или пароль.'),
  'trigger.triggerType': entry('trigger', 'Trigger type', 'Планируемый источник запуска: manual, webhook, schedule, event, message, file или api-call. Слушатели и расписание не запускаются.'),
  'trigger.source': entry('trigger', 'Источник', 'Откуда поступает событие: сервис, канал, файл или условие ручного запуска.'),
  'trigger.payload': entry('trigger', 'Payload schema', 'Контракт данных, которые приходят вместе с событием запуска.'),
  'logic.logicType': entry('logic', 'Logic type', 'Тип логического шага: условие, выбор, маршрутизация, цикл, объединение, параллельность, повтор или допуск.'),
  'logic.conditions': entry('logic', 'Условия', 'Правила выбора дальнейшего пути, по одному на строку. Это описание для реализации.'),
  'logic.expression': entry('logic', 'Выражение', 'Текст выражения или псевдокод логики. Произвольный код в приложении не исполняется.'),
  'logic.branch.label': entry('logic', 'Название ветви', 'Понятное имя одного варианта результата проверки.'),
  'logic.branch.condition': entry('logic', 'Условие ветви', 'Когда выбирать эту ветвь. Ветви пока не привязываются автоматически к исходящим связям.'),
  'data.dataType': entry('data', 'Data type', 'Что представляет узел: JSON, базу, таблицу, файл, векторное хранилище, состояние или память.'),
  'data.persistence': entry('data', 'Тип хранения', 'Как долго и каким способом будущая система должна хранить данные.'),
  'data.source': entry('data', 'Источник', 'Происхождение данных или ссылка на систему, из которой их следует получать.'),
  'data.schema': entry('data', 'Схема данных', 'Ожидаемая структура содержимого этого источника или хранилища.'),
  'human.interactionType': entry('human', 'Interaction type', 'Какое участие нужно от человека: подтверждение, разрешение, ввод, проверка или решение.'),
  'human.instruction': entry('human', 'Вопрос / инструкция', 'Что показать человеку и какое действие от него ожидается.'),
  'human.response': entry('human', 'Ожидаемый ответ', 'Контракт ответа человека: например решение, комментарий или заполненные данные.'),
  'artifact.artifactType': entry('artifact', 'Artifact type', 'Вид результата: документ, код, изображение, видео, отчёт, набор данных, файл или JSON.'),
  'artifact.format': entry('artifact', 'Формат', 'Формат итогового материала, например Markdown, CSV, JSON или PDF.'),
  'artifact.storageTarget': entry('artifact', 'Место хранения', 'Планируемая папка, система или правило размещения результата. Сам файл здесь не создаётся.'),
  'artifact.schema': entry('artifact', 'Схема результата', 'Контракт содержимого итогового результата, если оно структурировано.'),
  'contract.format': entry('contracts', 'Формат контракта', 'Свободное описание подходит для черновика; JSON Schema формализует структуру; общая схема переиспользуется по ID.'),
  'contract.description': entry('contracts', 'Описание контракта', 'Объясните, какие данные передаются, какие поля нужны и какие ограничения важны.'),
  'contract.json': entry('contracts', 'JSON Schema', 'Формальная схема JSON: Draft-07 по умолчанию, 2020-12 через $schema. После редактирования нажмите «Применить JSON».'),
  'contract.reference': entry('contracts', 'Общая схема', 'Выберите схему из ресурсов проекта. Изменение общего определения затронет всех, кто на него ссылается.'),
  'port.name': entry('connections', 'Название порта', 'Именованная точка входа или выхода узла. Имя можно менять без потери ID.'),
  'port.direction': entry('connections', 'Направление порта', 'input принимает связь, output отправляет её. Связи создаются от выхода ко входу.'),
  'port.kind': entry('connections', 'Тип порта', 'Семантика подключения: Flow, Data, Tool access или Reference. Типы соединяемых портов должны быть совместимы.'),
  'port.contract': entry('contracts', 'Контракт порта', 'Какие данные допускаются в этой точке входа или выхода.'),
  'subworkflow.binding': entry('subworkflow', 'Привязка порта', 'Какому внутреннему порту соответствует внешний вход или выход Subworkflow. Доступны совместимые тип и направление.'),
  'edge.type': entry('connections', 'Тип связи', 'Flow передаёт управление, Data — данные, Tool access задаёт Agent → Tool, Reference описывает зависимость.'),
  'edge.label': entry('connections', 'Подпись', 'Коротко объясните смысл связи или название передаваемых данных.'),
  'edge.condition': entry('connections', 'Условие', 'При каком условии используется связь. Preview не вычисляет выражения и условия.'),
  'edge.contract': entry('contracts', 'Контракт связи', 'Описание или схема данных, передаваемых по этой конкретной связи.'),
  'group.title': entry('organization', 'Название группы', 'Название визуальной подсистемы. Группа объединяет узлы, но не создаёт отдельный runtime.'),
  'group.description': entry('organization', 'Описание группы', 'Назначение подсистемы и границы ответственности входящих в неё узлов.'),
  'group.color': entry('organization', 'Цвет группы', 'Визуальный акцент для различения подсистем; не влияет на семантику графа.'),
  'project.name': entry('storage', 'Название проекта', 'Имя в списке локальных проектов и экспортируемых документах. Идентификатор проекта остаётся прежним.'),
  'project.description': entry('storage', 'Описание проекта', 'Цель системы, её пользователи, границы и ожидаемый итог работы.'),
  'project.mode': entry('workspace', 'Режим по умолчанию', 'Concept — работа с идеями; Engineering — инженерное представление. Режим не преобразует типы узлов.'),
  'project.grid': entry('canvas', 'Сетка', 'Показывает ориентиры для расположения узлов на Canvas.'),
  'project.snap': entry('canvas', 'Привязка к сетке', 'Выравнивает положение перемещаемых карточек по шагам сетки.'),
  'project.motion': entry('canvas', 'Анимация', 'Использовать системное предпочтение движения или уменьшить анимацию в этом проекте.'),
  'project.export': entry('export', 'Экспорт по умолчанию', 'Формат, заранее выбранный при открытии экспорта. Перед скачиванием его можно изменить.'),
  'resource.schemaName': entry('resources', 'Название схемы', 'Понятное имя общей схемы. Ссылки используют устойчивый ID и переживают переименование.'),
  'resource.promptName': entry('resources', 'Название prompt', 'Имя общего набора инструкций, на который могут ссылаться несколько агентов.'),
} as const
export type FieldHelpKey = keyof typeof fieldHelp
export function configHelpKey(type: string, path: string): FieldHelpKey | undefined {
  const qualified = `${type}.${path}`
  if (qualified in fieldHelp) return qualified as FieldHelpKey
  if (path in fieldHelp) return path as FieldHelpKey
  return undefined
}
