import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('almanac: browse, search body text, empty state, export entire offline book and return to editor', async ({ page, context }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await page.getByRole('button', { name: '◇ Concept Node' }).click()
  await page.getByRole('textbox', { name: 'Название', exact: true }).fill('Сохранить мой граф')
  await page.getByRole('button', { name: 'Альманах', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Альманах Workflow Architect' })
  const article = dialog.getByRole('article')
  await expect(article.getByRole('heading', { name: 'Что такое Workflow Architect' })).toBeVisible()
  await page.screenshot({ path: 'test-results/almanac-overview.png' })
  await dialog.getByRole('button', { name: /Agent: роль/ }).click()
  await expect(article.getByRole('heading', { name: 'Agent: роль, модель и инструкции' })).toBeFocused()
  await expect(article).toContainText('Connected tools')
  const search = dialog.getByRole('searchbox', { name: 'Поиск по альманаху' })
  await search.fill('additionalProperties')
  await expect(dialog.getByRole('status')).toHaveText('Найдено глав: 1')
  await expect(article.getByRole('heading', { name: 'Контракты и JSON Schema' })).toBeVisible()
  await page.screenshot({ path: 'test-results/almanac-search.png' })
  await search.fill('неттакойглавы987')
  await expect(dialog.getByRole('heading', { name: 'Главы не найдены' })).toBeVisible()
  await dialog.getByRole('button', { name: 'Сбросить поиск' }).click()
  await search.fill('контракт')
  const pending = page.waitForEvent('download')
  await dialog.getByRole('button', { name: 'Сохранить альманах' }).click()
  const download = await pending
  expect(download.suggestedFilename()).toBe('Workflow-Architect-Almanac-0.2.html')
  const html = await readFile((await download.path())!, 'utf8')
  expect(html).toContain('Что такое Workflow Architect')
  expect(html).toContain('Границы версии и частые вопросы')
  expect(html).not.toContain('<script')
  const offline = await context.newPage()
  await offline.setContent(html)
  const chapterLinks = offline.getByRole('navigation', { name: 'Оглавление' }).getByRole('link')
  expect(await chapterLinks.count()).toBeGreaterThanOrEqual(27)
  await chapterLinks.filter({ hasText: 'Словарь терминов' }).click()
  await expect(offline.getByRole('heading', { name: 'Словарь терминов' })).toBeInViewport()
  await offline.screenshot({ path: 'test-results/almanac-offline.png' })
  await offline.close()
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Альманах', exact: true })).toBeFocused()
  await expect(page.locator('.react-flow__node')).toContainText('Сохранить мой граф')
  expect(errors).toEqual([])
})

test('F1 opens from a text field; compact window keeps chapter and close controls accessible', async ({ page }) => {
  await page.setViewportSize({ width: 1000, height: 700 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await page.getByRole('textbox', { name: 'Название проекта', exact: true }).focus()
  await page.keyboard.press('F1')
  const dialog = page.getByRole('dialog', { name: 'Альманах Workflow Architect' })
  await expect(dialog).toBeVisible()
  await dialog.getByRole('button', { name: /Горячие клавиши/ }).click()
  await expect(dialog.getByRole('article')).toContainText('Ctrl+Shift+Z')
  await dialog.getByRole('button', { name: 'Следующая глава →' }).click()
  await expect(dialog.getByRole('heading', { name: 'Словарь терминов' })).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Закрыть диалог' })).toBeInViewport()
  expect(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/almanac-compact.png' })
  await page.keyboard.press('Escape')
  await expect(page.getByRole('textbox', { name: 'Название проекта', exact: true })).toBeFocused()
})
