import { expect, test } from '@playwright/test'

test('two windows preserve both edits and let the stale writer continue in a separate project', async ({ page, context }) => {
  await page.goto('/')
  await expect(page.locator('.save-status')).toContainText('Сохранено')
  const other = await context.newPage()
  await other.goto('/')
  await expect(other.locator('.save-status')).toContainText('Сохранено')
  const firstName = page.getByRole('textbox', { name: 'Название проекта', exact: true })
  await firstName.fill('First window'); await firstName.press('Enter')
  await expect(page.locator('.save-status')).toContainText('Сохранено')
  const secondName = other.getByRole('textbox', { name: 'Название проекта', exact: true })
  await secondName.fill('Second window'); await secondName.press('Enter')
  await expect(other.getByRole('alert')).toContainText('Проект изменён в другом окне')
  await expect(secondName).toHaveValue('Second window')
  await other.getByRole('button', { name: 'Сохранить мои правки отдельной копией' }).click()
  await expect(other.locator('.save-status')).toContainText('Сохранено')
  await other.getByRole('button', { name: 'Открыть проекты' }).click()
  const projects = other.getByRole('dialog', { name: 'Локальные проекты' })
  await expect(projects.locator('.project-list')).toContainText('First window')
  await expect(projects.locator('.project-list')).toContainText('Second window — моя копия')
  await projects.getByRole('button', { name: /First window/ }).click()
  await expect(secondName).toHaveValue('First window')
  await expect(other.locator('.save-status')).toContainText('Сохранено')
})
