import { expect, test } from '@playwright/test'

test('create, rename, connect, move, undo, resize and recover after reload', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Сначала замысел.' })).toBeVisible()
  await page.screenshot({ path: 'test-results/empty-state.png' })
  const add = page.getByRole('button', { name: '◇ Concept Node' })
  await add.click()
  await page.getByRole('textbox', { name: 'Название', exact: true }).fill('Исследовать')
  await page.getByRole('textbox', { name: 'Описание', exact: true }).click()
  await add.click()
  await page.getByRole('textbox', { name: 'Название', exact: true }).fill('Проверить')
  await page.getByRole('textbox', { name: 'Описание', exact: true }).fill('Оценить результат исследования')
  await page.getByRole('textbox', { name: 'Заметки', exact: true }).click()
  await expect(page.locator('.react-flow__node')).toHaveCount(2)
  const first = page.locator('.react-flow__node').filter({ hasText: 'Исследовать' })
  const second = page.locator('.react-flow__node').filter({ hasText: 'Проверить' })
  await first.locator('.source').dragTo(second.locator('.target'))
  await expect(page.locator('.react-flow__edge')).toHaveCount(1)
  const box = await first.boundingBox()
  if (!box) throw new Error('Node missing')
  await page.mouse.move(box.x + 70, box.y + 50)
  await page.mouse.down(); await page.mouse.move(box.x + 70, box.y + 230, { steps: 12 }); await page.mouse.up()
  const moved = await first.boundingBox()
  expect(moved!.y).toBeGreaterThan(box.y + 100)
  await page.getByRole('button', { name: 'Отменить', exact: true }).click()
  await expect.poll(async () => (await first.boundingBox())!.y).toBeCloseTo(box.y, 0)
  await page.getByRole('button', { name: 'Повторить', exact: true }).click()
  await expect.poll(async () => (await first.boundingBox())!.y).toBeGreaterThan(box.y + 100)
  await first.click()
  const handle = first.locator('.react-flow__resize-control.handle.bottom.right')
  const resize = await handle.boundingBox()
  if (!resize) throw new Error('Resize handle missing')
  const oldWidth = (await first.boundingBox())!.width
  await page.mouse.move(resize.x + resize.width / 2, resize.y + resize.height / 2)
  await page.mouse.down(); await page.mouse.move(resize.x + 65, resize.y + 45, { steps: 10 }); await page.mouse.up()
  expect((await first.boundingBox())!.width).toBeGreaterThan(oldWidth + 30)
  await page.getByRole('button', { name: 'Отменить', exact: true }).click()
  await expect.poll(async () => (await first.boundingBox())!.width).toBeCloseTo(oldWidth, 0)
  await page.getByRole('button', { name: 'Повторить', exact: true }).click()
  await expect(page.locator('.save-status')).toContainText('Сохранено')
  await page.screenshot({ path: 'test-results/concept-canvas.png' })
  await page.reload()
  await expect(page.locator('.react-flow__node')).toHaveCount(2)
  await expect(page.locator('.react-flow__edge')).toHaveCount(1)
  await expect(first).toContainText('Исследовать')
  await expect(second).toContainText('Оценить результат исследования')
  await first.click(); await page.keyboard.press('Delete')
  await expect(page.locator('.react-flow__node')).toHaveCount(1)
  await expect(page.locator('.react-flow__edge')).toHaveCount(0)
  await page.keyboard.press('Control+z')
  await expect(page.locator('.react-flow__node')).toHaveCount(2)
  await expect(page.locator('.react-flow__edge')).toHaveCount(1)
  expect(errors).toEqual([])
})

test('damaged local data is recoverable and never overwritten during boot', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('.save-status')).toContainText('Сохранено')
  await page.evaluate(async () => {
    await new Promise<void>((resolve, reject) => {
      const request = indexedDB.open('workflow-architect', 1)
      request.onerror = () => reject(request.error)
      request.onsuccess = () => {
        const db = request.result
        const tx = db.transaction(['projects', 'preferences'], 'readwrite')
        tx.objectStore('projects').put('{broken', 'damaged')
        tx.objectStore('preferences').put('damaged', 'active-project')
        tx.oncomplete = () => { db.close(); resolve() }
        tx.onerror = () => reject(tx.error)
      }
    })
  })
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Не удалось открыть проект' })).toBeVisible()
  await expect(page.getByText('Сохранённые данные не перезаписаны.')).toBeVisible()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать исходный JSON' }).click()
  expect((await download).suggestedFilename()).toBe('project-recovery.json')
})

test('keyboard edits, multi-selection and compact Canvas at a smaller desktop viewport', async ({ page }) => {
  await page.setViewportSize({ width: 1100, height: 800 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  const add = page.getByRole('button', { name: '◇ Concept Node' })
  await add.click(); await add.click()
  await page.getByRole('button', { name: 'Fit View', exact: true }).click()
  const nodes = page.locator('.react-flow__node')
  await nodes.first().click()
  await nodes.nth(1).click({ modifiers: ['Shift'] })
  await expect(page.locator('.react-flow__node.selected')).toHaveCount(2)
  await expect(page.getByRole('heading', { name: 'Выбрано: 2' })).toBeVisible()
  await page.keyboard.press('Delete')
  await expect(nodes).toHaveCount(0)
  await page.keyboard.press('Control+z')
  await expect(nodes).toHaveCount(2)
  await nodes.first().click()
  const originalY = (await nodes.first().boundingBox())!.y
  await page.keyboard.press('ArrowDown')
  await expect.poll(async () => (await nodes.first().boundingBox())!.y).toBeGreaterThan(originalY + 5)
  await page.keyboard.press('Control+z')
  await expect.poll(async () => (await nodes.first().boundingBox())!.y).toBeCloseTo(originalY, 0)
  const title = page.getByRole('textbox', { name: 'Название', exact: true })
  await title.fill('Текст'); await title.press('Backspace')
  await expect(nodes).toHaveCount(2)
  await title.press('Enter')
  for (let i = 0; i < 4; i++) await page.getByRole('button', { name: 'Zoom Out', exact: true }).click()
  await expect(page.locator('.workflow-card.compact')).toHaveCount(2)
  await nodes.first().focus()
  await page.screenshot({ path: 'test-results/compact-focus.png' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
