import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('formalize a concept, configure agent, link schema, edit a data contract and persist', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('/')
  const add = page.getByRole('button', { name: '◇ Concept Node' })
  await add.click()
  const title = page.getByRole('textbox', { name: 'Название', exact: true })
  await title.fill('Исследователь'); await title.press('Enter')
  const first = page.locator('.react-flow__node').filter({ hasText: 'Исследователь' })
  const id = await first.getAttribute('data-id')
  await page.getByRole('combobox', { name: 'Преобразовать в' }).selectOption('agent')
  await expect(first).toContainText('AGENT')
  expect(await first.getAttribute('data-id')).toBe(id)
  await page.getByRole('button', { name: 'Отменить', exact: true }).click()
  await expect(first).toContainText('CONCEPT')
  await page.getByRole('button', { name: 'Повторить', exact: true }).click()
  await page.getByRole('textbox', { name: 'Роль', exact: true }).fill('Исследовать источники')
  await page.getByRole('textbox', { name: 'System prompt', exact: true }).fill('# Задача\nПроверяй источники.')
  await page.getByRole('textbox', { name: 'Provider', exact: true }).fill('Local')
  await page.getByRole('textbox', { name: 'Model', exact: true }).fill('research-model')
  await page.getByRole('textbox', { name: 'Model', exact: true }).press('Enter')
  await page.getByRole('button', { name: 'Развернуть prompt' }).click()
  await expect(page.getByRole('dialog', { name: 'System prompt · Markdown' })).toBeVisible()
  await expect(page.locator('.cm-content')).toContainText('Проверяй источники.')
  await page.getByRole('button', { name: 'Применить prompt' }).click()
  await page.getByRole('button', { name: 'Схемы и prompts', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Общие схемы и prompts' })
  await dialog.getByRole('button', { name: '＋ Общая схема' }).click()
  await dialog.getByRole('textbox', { name: 'Название схемы' }).fill('ResearchRequest')
  await dialog.getByRole('textbox', { name: 'Название схемы' }).press('Enter')
  await dialog.getByRole('textbox', { name: 'JSON Schema', exact: true }).fill('{"type":"invalid"}')
  await dialog.getByRole('button', { name: 'Применить JSON' }).click()
  await expect(dialog.getByRole('alert')).toBeVisible()
  await dialog.getByRole('textbox', { name: 'JSON Schema', exact: true }).fill('{"type":"object","properties":{"topic":{"type":"string"}}}')
  await dialog.getByRole('button', { name: 'Применить JSON' }).click()
  await expect(dialog.getByRole('alert')).toHaveCount(0)
  await dialog.getByRole('button', { name: 'Закрыть диалог' }).click()
  await page.getByRole('combobox', { name: 'Входной контракт: формат' }).selectOption('schema-ref')
  await expect(page.getByRole('combobox', { name: 'Входной контракт: схема' })).toContainText('ResearchRequest')
  await page.getByRole('combobox', { name: 'Выходной контракт: формат' }).selectOption('informal')
  await page.getByRole('textbox', { name: 'Выходной контракт: описание' }).fill('Проверенный отчёт')
  await add.click()
  const second = page.locator('.react-flow__node').filter({ hasText: 'Новая идея' })
  await first.locator('.source').dragTo(second.locator('.target'))
  const edge = page.locator('.react-flow__edge')
  await expect(edge).toHaveCount(1)
  await edge.focus(); await page.keyboard.press('Enter')
  await page.getByRole('combobox', { name: 'Тип связи', exact: true }).selectOption('data')
  await page.getByRole('combobox', { name: 'Контракт связи: формат' }).selectOption('schema-ref')
  await page.getByRole('textbox', { name: 'Подпись', exact: true }).fill('Research request')
  await page.getByRole('textbox', { name: 'Подпись', exact: true }).press('Enter')
  await page.getByRole('button', { name: 'Validate', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Проверка проекта' })).toContainText('0 Errors')
  await page.getByRole('button', { name: 'Режим редактора' }).click()
  await expect(page.getByRole('button', { name: 'Режим редактора' })).toHaveText('Engineering')
  await expect(page.locator('.save-status')).toContainText('Сохранено')
  await page.screenshot({ path: 'test-results/engineering-contract.png' })
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Экспорт', exact: false }).click()
  await page.getByRole('button', { name: 'JSON snapshot' }).click()
  await page.getByRole('button', { name: 'Скачать экспорт' }).click()
  const download = await downloadPromise
  const file = await download.path()
  const project = JSON.parse(await readFile(file!, 'utf8'))
  expect(project.nodes[0].id).toBe(id)
  expect(project.nodes[0].config.model).toEqual({ provider: 'Local', name: 'research-model' })
  expect(project.nodes[0].config.input.schemaId).toBe(project.schemas[0].id)
  expect(project.edges[0].type).toBe('data')
  await page.reload()
  await expect(first).toContainText('AGENT')
  await first.click()
  await expect(page.getByRole('textbox', { name: 'Model', exact: true })).toHaveValue('research-model')
  await page.getByRole('textbox', { name: 'Model', exact: true }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: 'test-results/engineering-inspector.png' })
  expect(errors).toEqual([])
})

test('all engineering node types are creatable with their own configuration fields', async ({ page }) => {
  await page.goto('/')
  const cases = [
    ['Tool', 'Authentication', 'environment'], ['Trigger', 'Trigger type', 'webhook'], ['Logic', 'Logic type', 'router'],
    ['Data', 'Data type', 'json'], ['Human', 'Interaction type', 'review'], ['Artifact', 'Artifact type', 'document'],
  ]
  for (const [name, field, value] of cases) {
    await page.locator('.library-item').filter({ has: page.getByText(name!, { exact: true }) }).click()
    await page.getByRole('combobox', { name: field!, exact: true }).selectOption(value!)
    await expect(page.getByRole('combobox', { name: field!, exact: true })).toHaveValue(value!)
  }
  await page.locator('.library-item').filter({ has: page.getByText('Subworkflow', { exact: true }) }).click()
  await expect(page.locator('.react-flow__node')).toHaveCount(7)
  await expect(page.getByRole('alert')).toHaveCount(0)
})
