import { expect, test, type Page } from './fixtures'
import { readFile } from 'node:fs/promises'
import { unzipSync, strFromU8 } from 'fflate'
import { createEdge, createId, createNode, createProject } from '../src/domain/factories'

async function download(page: Page) {
  const pending = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать экспорт' }).click()
  return readFile((await (await pending).path())!)
}

test('preview and export Codex/Markdown/YAML, import ZIP and canonical JSON pair without losing nested graphs', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('/')
  await page.getByRole('button', { name: '✦ Agent' }).click()
  await page.getByRole('button', { name: '⌁ Tool' }).click()
  await page.getByRole('application').click({ position: { x: 40, y: 40 } })
  await page.keyboard.press('Control+a'); await page.keyboard.press('g')
  await page.getByRole('button', { name: 'Преобразовать в Subworkflow', exact: true }).click()
  await page.getByRole('button', { name: /^Экспорт/ }).click()
  const dialog = page.getByRole('dialog', { name: 'Экспорт проекта' })
  await dialog.getByRole('button', { name: 'Codex package' }).click()
  await dialog.getByRole('combobox', { name: 'Предпросмотр файла' }).selectOption('IMPLEMENTATION_PLAN.md')
  await expect(dialog.getByLabel('Текст файла')).toContainText('What to build')
  await expect(dialog.getByRole('button', { name: 'Скачать экспорт' })).toBeEnabled()
  await page.screenshot({ path: 'test-results/export-codex.png' })
  const zip = await download(page), files = unzipSync(zip)
  expect(Object.keys(files)).toContain('AGENTS.md')
  const workflow = JSON.parse(strFromU8(files['workflow.json']!))
  expect(workflow.subworkflows).toHaveLength(1)
  expect(workflow.subworkflows[0].nodes).toHaveLength(2)
  await dialog.getByRole('button', { name: 'Markdown architecture' }).click()
  expect((await download(page)).toString()).toContain('## Subworkflows')
  await dialog.getByRole('button', { name: 'YAML snapshot' }).click()
  const yaml = await download(page)
  expect(yaml.toString()).toContain('schemaVersion:')
  await dialog.getByRole('button', { name: 'Закрыть диалог' }).click()
  await page.getByRole('button', { name: 'Открыть проекты' }).click()
  const projects = page.getByRole('dialog', { name: 'Локальные проекты' })
  await projects.getByLabel('Файл проекта').setInputFiles({ name: 'codex-package.zip', mimeType: 'application/zip', buffer: zip })
  await projects.getByRole('button', { name: 'Открыть импорт' }).click()
  await expect(page.locator('.react-flow__node-workflow')).toHaveCount(1)
  await expect(page.getByRole('button', { name: 'Открыть проекты' })).toContainText('— импорт')
  await page.getByRole('button', { name: 'Открыть проекты' }).click()
  await projects.getByLabel('Файл проекта').setInputFiles(['project.json', 'workflow.json'].map(name => ({ name, mimeType: 'application/json', buffer: Buffer.from(files[name]!) })))
  await projects.getByRole('button', { name: 'Открыть импорт' }).click()
  await page.getByRole('button', { name: 'Открыть проекты' }).click()
  await projects.getByLabel('Файл проекта').setInputFiles({ name: 'project.yaml', mimeType: 'application/yaml', buffer: yaml })
  await projects.getByRole('button', { name: 'Открыть импорт' }).click()
  await page.locator('.react-flow__node-workflow').dblclick()
  await expect(page.locator('.react-flow__node-workflow')).toHaveCount(2)
  await page.reload()
  await page.locator('.react-flow__node-workflow').dblclick()
  await expect(page.locator('.react-flow__node-workflow')).toHaveCount(2)
  expect(errors).toEqual([])
})

test('engineering errors block packages while raw export remains available with clear diagnostics', async ({ page }) => {
  const project = createProject('Repairable draft'), node = createNode('concept')
  project.nodes.push(node)
  project.edges.push(createEdge(node.id, createId()))
  await page.goto('/')
  await page.getByRole('button', { name: 'Открыть проекты' }).click()
  await page.getByLabel('Файл проекта').setInputFiles({ name: 'broken-link.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(project)) })
  await page.getByRole('button', { name: 'Открыть импорт' }).click()
  await page.getByRole('button', { name: /^Экспорт/ }).click()
  const dialog = page.getByRole('dialog', { name: 'Экспорт проекта' })
  await expect(dialog.getByRole('alert')).toContainText('Engineering export')
  await expect(dialog.getByRole('button', { name: 'Скачать экспорт' })).toBeDisabled()
  await page.screenshot({ path: 'test-results/export-error.png' })
  await dialog.getByRole('button', { name: 'JSON snapshot' }).click()
  expect(JSON.parse((await download(page)).toString()).edges[0].targetNode).toBe(project.edges[0]!.targetNode)
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
})
