import { expect, test, type Page } from './fixtures'

async function node(page: Page, title: string) {
  await page.getByRole('button', { name: '◇ Concept Node' }).click()
  const field = page.getByRole('textbox', { name: 'Название', exact: true })
  await field.fill(title); await field.press('Enter')
}

test('group movement, collapse, conversion, nested navigation, search and scoped undo survive reload', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('/')
  await node(page, 'Input'); await node(page, 'Research'); await node(page, 'Review')
  await page.getByRole('button', { name: 'Fit View', exact: true }).click()
  const input = page.locator('.react-flow__node-workflow').filter({ hasText: 'Input' })
  const research = page.locator('.react-flow__node-workflow').filter({ hasText: 'Research' })
  const review = page.locator('.react-flow__node-workflow').filter({ hasText: 'Review' })
  await input.locator('.source').dragTo(research.locator('.target'))
  await research.locator('.source').dragTo(review.locator('.target'))
  await research.click(); await review.click({ modifiers: ['Shift'] })
  await page.keyboard.press('g')
  await expect(page.locator('.react-flow__node-workflow-group')).toHaveCount(1)
  const groupName = page.getByRole('textbox', { name: 'Название группы' })
  await groupName.fill('Research pipeline'); await groupName.press('Enter')
  await page.getByRole('button', { name: 'Fit View', exact: true }).click()
  const before = (await research.boundingBox())!
  const header = page.locator('.group-header')
  const box = (await header.boundingBox())!
  await page.mouse.move(box.x + 60, box.y + 15); await page.mouse.down()
  await page.mouse.move(box.x + 60, box.y + 110, { steps: 10 }); await page.mouse.up()
  await expect.poll(async () => (await research.boundingBox())!.y).toBeGreaterThan(before.y + 40)
  await page.keyboard.press('Control+z')
  await expect.poll(async () => (await research.boundingBox())!.y).toBeCloseTo(before.y, 0)
  await header.getByRole('button', { name: 'Свернуть группу' }).click()
  await expect(research).toBeHidden(); await expect(review).toBeHidden()
  await expect(page.locator('.react-flow__edge')).toHaveCount(1)
  await page.screenshot({ path: 'test-results/collapsed-group.png' })
  await header.getByRole('button', { name: 'Развернуть группу' }).click()
  await header.click()
  await page.getByRole('button', { name: 'Преобразовать в Subworkflow', exact: true }).click()
  await expect(page.locator('.react-flow__node-workflow-group')).toHaveCount(0)
  const wrapper = page.locator('.react-flow__node-workflow').filter({ hasText: 'Research pipeline' })
  await expect(wrapper).toContainText('SUBWORKFLOW')
  await expect(page.locator('.react-flow__edge')).toHaveCount(1)
  await wrapper.dblclick()
  await expect(page.getByRole('navigation', { name: 'Путь workflow' })).toContainText('Research pipeline')
  await expect(page.locator('.react-flow__node-workflow')).toHaveCount(2)
  await expect(page.locator('.react-flow__edge')).toHaveCount(1)
  await research.click()
  const name = page.getByRole('textbox', { name: 'Название', exact: true })
  await name.fill('Find sources'); await name.press('Enter')
  await page.getByRole('navigation', { name: 'Путь workflow' }).getByRole('button', { name: 'Новый workflow' }).click()
  await page.keyboard.press('Control+z')
  await expect(page.getByRole('navigation', { name: 'Путь workflow' }).getByRole('button', { name: 'Research pipeline' })).toHaveAttribute('aria-current', 'page')
  await expect(research).toBeVisible()
  await page.keyboard.press('Control+Shift+z')
  await page.getByRole('navigation', { name: 'Путь workflow' }).getByRole('button', { name: 'Новый workflow' }).click()
  await page.keyboard.press('Control+f')
  const search = page.getByRole('dialog', { name: 'Поиск по проекту' })
  await search.getByRole('textbox', { name: 'Поиск узлов и тегов' }).fill('Find sources')
  await search.getByRole('button', { name: /Find sources/ }).click()
  await expect(page.locator('.react-flow__node.selected')).toContainText('Find sources')
  await page.screenshot({ path: 'test-results/nested-workflow.png' })
  await expect(page.locator('.save-status')).toContainText('Сохранено')
  await page.reload()
  await expect(wrapper).toBeVisible()
  await wrapper.dblclick()
  await expect(page.locator('.react-flow__node-workflow').filter({ hasText: 'Find sources' })).toBeVisible()
  expect(errors).toEqual([])
})

test('palette, copy/paste, duplicate, alignment, context menu, fit-selection and help are keyboard accessible', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('application')).toBeVisible()
  await page.keyboard.press('Control+k')
  const palette = page.getByRole('dialog', { name: 'Команды и узлы' })
  await palette.getByRole('combobox', { name: 'Поиск команд' }).fill('Concept')
  await page.keyboard.press('Enter')
  await expect(page.locator('.react-flow__node-workflow')).toHaveCount(1)
  await page.keyboard.press('Control+c'); await page.keyboard.press('Control+v')
  await expect(page.locator('.react-flow__node-workflow')).toHaveCount(2)
  await page.keyboard.press('Control+d')
  await expect(page.locator('.react-flow__node-workflow')).toHaveCount(3)
  await page.keyboard.press('Control+a')
  await page.getByRole('button', { name: 'По верхнему краю', exact: true }).click()
  await expect.poll(async () => {
    const ys = await page.locator('.react-flow__node-workflow').evaluateAll(nodes => nodes.map(n => n.getBoundingClientRect().y))
    return Math.max(...ys) - Math.min(...ys)
  }).toBeLessThan(1)
  await page.keyboard.press('Control+z')
  await page.keyboard.press('Shift+f')
  await page.getByRole('button', { name: 'Fit View', exact: true }).click()
  await page.keyboard.press('Escape')
  await page.locator('.react-flow__node-workflow').last().click({ button: 'right' })
  await expect(page.getByRole('menu', { name: 'Контекстное меню' })).toBeVisible()
  await page.getByRole('menuitem', { name: 'Convert → Agent' }).click()
  await expect(page.locator('.react-flow__node-workflow').last()).toContainText('AGENT')
  await page.keyboard.press('Control+z')
  await page.getByRole('button', { name: 'Альманах', exact: true }).click()
  const handbook = page.getByRole('dialog', { name: 'Альманах Workflow Architect' })
  await handbook.getByRole('button', { name: /Горячие клавиши/ }).click()
  await expect(handbook.getByRole('article')).toContainText('Палитра команд')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
})
