import { expect, test } from '@playwright/test'

test('setup, manual preferences and two profiles survive reload without altering projects', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Имя профиля', { exact: true }).fill('Михаил')
  await page.getByLabel('Что хотите получить от приложения?').fill('Исследование и анализ')
  await page.getByLabel('Опыт проектирования процессов').selectOption('advanced')
  await page.getByLabel('Предпочтительный способ управления').selectOption('manual')
  await page.getByRole('button', { name: 'Далее', exact: true }).click()
  await page.getByLabel('Trigger → Agent → Artifact').check()
  await page.getByRole('button', { name: 'Проверить ответ' }).click()
  await expect(page.getByRole('status')).toContainText('Верно')
  await page.getByRole('button', { name: 'К рекомендациям' }).click()
  await expect(page.getByLabel('Плотность интерфейса')).toHaveValue('compact')
  await expect(page.getByLabel('Multi-agent Research', { exact: true })).toBeChecked()
  await page.getByLabel('Движение интерфейса').selectOption('reduced')
  await page.screenshot({ path: 'test-results/setup-preferences.png', fullPage: true })
  await page.getByRole('button', { name: 'Сохранить и открыть редактор' }).click()
  await expect(page.getByRole('application')).toBeVisible()
  await expect(page.locator('.app-shell')).toHaveAttribute('data-density', 'compact')
  await expect(page.locator('.app-shell')).toHaveAttribute('data-motion', 'reduced')
  await expect(page.getByRole('button', { name: 'Режим редактора' })).toHaveText('Engineering')
  await expect(page.locator('.react-flow__node-workflow')).toHaveCount(0)
  await page.keyboard.press('a')
  await page.getByRole('textbox', { name: 'Название', exact: true }).fill('Мой агент')
  await page.getByRole('button', { name: 'Профили: Михаил' }).click()
  await page.getByRole('button', { name: 'Профиль 2 · переключиться' }).click()
  await expect(page.getByRole('heading', { name: 'Настроим приложение под вас' })).toBeVisible()
  await page.getByRole('button', { name: 'Пропустить настройку' }).click()
  await expect(page.locator('.react-flow__node-workflow')).toHaveCount(0)
  await expect(page.locator('.app-shell')).toHaveAttribute('data-density', 'comfortable')
  await page.getByRole('button', { name: 'Профили: Профиль 2' }).click()
  await page.getByLabel('Имя профиля', { exact: true }).fill('Второй пользователь')
  await page.getByRole('button', { name: 'Сохранить настройки профиля' }).click()
  await expect(page.getByRole('button', { name: 'Профили: Второй пользователь' })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'Профили: Второй пользователь' }).click()
  await page.getByRole('button', { name: 'Михаил · переключиться' }).click()
  await expect(page.locator('.react-flow__node-workflow')).toContainText('Мой агент')
  const snapshots = await page.evaluate(() => new Promise<string[]>((resolve, reject) => {
    const request = indexedDB.open('workflow-architect', 1)
    request.onsuccess = () => {
      const db = request.result
      const read = db.transaction('projects').objectStore('projects').getAll()
      read.onsuccess = () => { resolve(read.result as string[]); db.close() }
      read.onerror = () => reject(read.error)
    }
    request.onerror = () => reject(request.error)
  }))
  expect(snapshots.join('')).not.toContain('Исследование и анализ')
  expect(snapshots.join('')).not.toContain('favoriteTemplates')
  await expect(page.locator('.app-shell')).toHaveAttribute('data-density', 'compact')
  await page.getByRole('button', { name: 'Профили: Михаил' }).click()
  await page.getByRole('button', { name: 'Пройти настройку заново' }).click()
  await expect(page.getByLabel('Что хотите получить от приложения?')).toHaveValue('Исследование и анализ')
  await page.getByRole('dialog', { name: 'Локальные профили' }).getByRole('button', { name: 'Отменить', exact: true }).click()
  await page.keyboard.press('Escape')
  await expect(page.locator('.react-flow__node-workflow')).toContainText('Мой агент')
})

test('guided sections remain accessible and manual edits do not require setup or network', async ({ page }) => {
  await page.setViewportSize({ width: 1000, height: 700 })
  await page.goto('/')
  await page.getByRole('button', { name: 'Пропустить настройку' }).click()
  await expect(page.getByRole('application')).toBeVisible()
  await page.getByRole('button', { name: 'Профили: Профиль 1' }).click()
  await page.getByLabel('Подробность Inspector').selectOption('guided')
  await page.screenshot({ path: 'test-results/profile-settings-compact.png', animations: 'disabled' })
  await page.getByRole('button', { name: 'Сохранить настройки профиля' }).click()
  await page.keyboard.press('a')
  const sections = page.locator('.inspector details.inspector-section')
  await expect(sections.first()).toHaveAttribute('open', '')
  const closed = page.locator('.inspector details.inspector-section:not([open])').first()
  await expect(closed).toBeVisible()
  await closed.locator('summary').click()
  await expect(page.locator('.inspector details.inspector-section[open]')).not.toHaveCount(0)
  await page.screenshot({ path: 'test-results/profile-guided.png' })
})

test('a project write conflict prevents profile switching and preserves the local editor', async ({ page, context }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Пропустить настройку' }).click()
  await expect(page.getByRole('application')).toBeVisible()
  await page.keyboard.press('a')
  await expect(page.locator('.save-status')).toContainText('Сохранено')
  const other = await context.newPage()
  await other.goto('/')
  await other.locator('.react-flow__node-workflow').click()
  await page.getByRole('textbox', { name: 'Название', exact: true }).fill('Из другого окна')
  await page.getByRole('textbox', { name: 'Название', exact: true }).press('Tab')
  await expect(page.locator('.save-status')).toContainText('Сохранено')
  await other.getByRole('textbox', { name: 'Название', exact: true }).fill('Мои несохранённые изменения')
  await other.getByRole('button', { name: 'Профили: Профиль 1' }).click()
  await other.getByRole('button', { name: 'Профиль 2 · переключиться' }).click()
  await expect(other.getByRole('dialog').getByRole('alert')).toContainText('Сначала сохраните текущий проект')
  await other.keyboard.press('Escape')
  await expect(other.locator('.react-flow__node-workflow')).toContainText('Мои несохранённые изменения')
  await expect(other.getByRole('button', { name: 'Профили: Профиль 1' })).toBeVisible()
  await other.close()
})
